repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.12.0
  hooks:
    # Run the linter.
    - id: ruff-check
      types_or: [ python, pyi ]  # removed jupyter from the list of allowed filetypes to avoid running the linter on notebooks
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
      types_or: [ python, pyi ]  # removed jupyter from the list of allowed filetypes to avoid running the formatter on notebooks